/*
Copyright 2026 The KubeFleet Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package placementpolicy contains the controller logic for reconciling placement policy objects: it
// snapshots the resources they select, schedules them onto matching member clusters via placement
// bindings, and submits cluster claims when no member cluster can satisfy a cluster selector.
package placementpolicy

import (
	"context"
	"time"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/klog/v2"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	placementv1alpha1 "github.com/kubefleet-dev/kubefleet/apis/kubefleet.dev/placement/v1alpha1"
	"github.com/kubefleet-dev/kubefleet/pkg/utils/errors"
	"github.com/kubefleet-dev/kubefleet/pkg/v1/managers/placementresourcesnapshot"
	"github.com/kubefleet-dev/kubefleet/pkg/v1/utils/bindingmanager"
)

const (
	controllerName = "PlacementPolicy"

	placementPolicyCleanupFinalizer = "placement.kubefleet.dev/placement-policy-cleanup"

	placementBindingNameFmt = "%s-%s"

	// clusterSelectorHashAnnotationKey records, on a placement binding generated by this controller, the hash
	// of the cluster selector it was created to fulfill. The current placement API tracks a binding's cluster
	// selectors via a hash kept in annotations (see the doc comment on PlacementBindingSpec.ClusterSelectors)
	// rather than a dedicated spec field, so this controller owns and manages the annotation key itself.
	clusterSelectorHashAnnotationKey = "placement.kubefleet.dev/placement-cluster-selector-hash"
)

type Reconciler struct {
	HubClient client.Client

	PlacementResourceSnapshotManager *placementresourcesnapshot.Manager
}

// placementPolicyObjectRef returns an ObjectReference that identifies the given placement policy itself.
//
// It is used to claim (and relinquish) the binding manager role for the placement policy: this
// controller always manages the bindings of the policy it is reconciling, so the object reference it
// claims the role with is always a reference to the placement policy itself.
func placementPolicyObjectRef(placementPolicy *placementv1alpha1.PlacementPolicy) placementv1alpha1.ObjectReference {
	return placementv1alpha1.ObjectReference{
		Namespace:  placementPolicy.Namespace,
		Name:       placementPolicy.Name,
		APIGroup:   placementv1alpha1.GroupVersion.Group,
		APIVersion: placementv1alpha1.GroupVersion.Version,
		Kind:       placementv1alpha1.PlacementPolicyKind,
	}
}

func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	startTime := time.Now()
	klog.V(2).InfoS("Reconciliation starts", "placementPolicy", req.NamespacedName, "controller", controllerName)
	defer func() {
		latency := time.Since(startTime).Milliseconds()
		klog.V(2).InfoS("Reconciliation ends", "placementPolicy", req.NamespacedName, "controller", controllerName, "latency", latency)
	}()

	// Retrieve the PlacementPolicy object.
	placement := &placementv1alpha1.PlacementPolicy{}
	err := r.HubClient.Get(ctx, req.NamespacedName, placement)
	switch {
	case apierrors.IsNotFound(err):
		// The placement cannot be found; it may have been deleted already. No need for
		// further reconciliation.
		klog.V(2).InfoS("The placement object cannot be found", "placementPolicy", req.NamespacedName, "controller", controllerName)
		return ctrl.Result{}, nil
	case err != nil:
		// An error occurred when trying to retrieve the placement; retry later.
		wrappedErr := errors.NewAPIServerError(err, "", true, "placementPolicy", req.NamespacedName, "controller", controllerName)
		klog.ErrorS(wrappedErr, "Failed to get the placement object", errors.Args(wrappedErr)...)
		return ctrl.Result{}, wrappedErr
	}

	if !placement.DeletionTimestamp.IsZero() {
		// Drop the finalizer if it exists.
		if controllerutil.ContainsFinalizer(placement, placementPolicyCleanupFinalizer) {
			controllerutil.RemoveFinalizer(placement, placementPolicyCleanupFinalizer)

			if err := r.HubClient.Update(ctx, placement); err != nil {
				wrappedErr := errors.NewAPIServerError(err, "", false, "placementPolicy", req.NamespacedName, "controller", controllerName)
				klog.ErrorS(wrappedErr, "Failed to remove finalizer from the deleted placement object", errors.Args(wrappedErr)...)
				return ctrl.Result{}, wrappedErr
			}
			klog.V(2).InfoS("Removed finalizer from the deleted placement object", "placementPolicy", req.NamespacedName, "controller", controllerName)
		}
		return ctrl.Result{}, nil

		// Other resources are cleaned up via their owner references.
	}

	// Add the cleanup finalizer if not already added.
	if !controllerutil.ContainsFinalizer(placement, placementPolicyCleanupFinalizer) {
		controllerutil.AddFinalizer(placement, placementPolicyCleanupFinalizer)
		if err := r.HubClient.Update(ctx, placement); err != nil {
			wrappedErr := errors.NewAPIServerError(err, "", false, "placementPolicy", req.NamespacedName, "controller", controllerName)
			klog.ErrorS(wrappedErr, "Failed to add cleanup finalizer", errors.Args(wrappedErr)...)
			return ctrl.Result{}, wrappedErr
		}
	}

	// Request a new resource snapshot if one hasn't been created yet for this placement.
	latestResourceSnapshot, isLatestResourceSnapshotPresentAndUpToDate, err := r.retrieveLatestResourceSnapshot(ctx, placement)
	if err != nil {
		klog.ErrorS(err, "Failed to check if the latest resource snapshot is up to date", errors.Args(err)...)
		return ctrl.Result{}, err
	}

	// Do some very basic scheduling.

	// Prep the selectors.
	selectors := placement.Spec.ClusterSelectors
	_, selectorSetByHash, err := prepareClusterSelectorsForScheduling(selectors)
	if err != nil {
		klog.ErrorS(err, "Failed to prepare cluster selectors for scheduling",
			append(errors.Args(err), "placementPolicy", req.NamespacedName)...)
		return ctrl.Result{}, err
	}

	// List all existing placement bindings owned by the placement policy.
	//
	// The current placement API has no label that tracks a binding's owner placement policy (unlike, say,
	// placement resource snapshots), so bindings are matched by their spec field instead of a label selector.
	bindingList := &placementv1alpha1.PlacementBindingList{}
	if err := r.HubClient.List(ctx, bindingList, client.InNamespace(placement.Namespace)); err != nil {
		wrappedErr := errors.NewAPIServerError(err, "failed to list placement bindings for the placement policy", false, "placementPolicy", klog.KObj(placement))
		klog.ErrorS(wrappedErr, "Failed to list placement bindings for the placement policy", errors.Args(wrappedErr)...)
		return ctrl.Result{}, wrappedErr
	}
	allBindings := make([]placementv1alpha1.PlacementBinding, 0, len(bindingList.Items))
	for idx := range bindingList.Items {
		if bindingList.Items[idx].Spec.PlacementPolicyName == placement.Name {
			allBindings = append(allBindings, bindingList.Items[idx])
		}
	}

	// If there are bindings that are marked for deletion but not deleted yet, wait until
	// they disappear.
	for idx := range allBindings {
		binding := allBindings[idx]
		if !binding.DeletionTimestamp.IsZero() {
			klog.V(2).InfoS("There are bindings that are marked for deletion but not deleted yet; requeue until they are fully removed",
				"placementPolicy", req.NamespacedName, "binding", klog.KObj(&binding))
			return ctrl.Result{RequeueAfter: time.Second * 10}, nil
		}
	}

	// Cross reference the selectors and the bindings; find the selectors that no longer have bindings, and
	// the bindings that no longer match with any of the selectors.
	danglingBindings := crossReferenceClusterSelectorsAndBindings(selectorSetByHash, allBindings)

	isSchedulingNeeded := needsScheduling(selectorSetByHash, danglingBindings)
	shouldRequeue := false
	if isSchedulingNeeded {
		shouldRequeue, err = r.scheduleOnce(
			ctx,
			placement,
			latestResourceSnapshot,
			selectors, selectorSetByHash,
			allBindings,
			danglingBindings,
		)
		if err != nil {
			wrappedErr := errors.Wraps(err, "", "placementPolicy", klog.KObj(placement))
			klog.ErrorS(wrappedErr, "Failed to perform scheduling for the placement policy", errors.Args(wrappedErr)...)
			return ctrl.Result{}, wrappedErr
		}
	}

	// Relinquish the binding manager role anyway so that other controllers can manipulate bindings if needed.
	if err := bindingmanager.RelinquishRoleFor(ctx, r.HubClient, placement, controllerName, placementPolicyObjectRef(placement)); err != nil {
		wrappedErr := errors.Wraps(err, "", "placementPolicy", klog.KObj(placement))
		klog.ErrorS(wrappedErr, "Failed to relinquish the binding manager role for the placement policy", errors.Args(wrappedErr)...)
		return ctrl.Result{}, wrappedErr
	}

	// Update the placement status.
	//
	// Note that status is updated even if scheduling is not needed and cannot be performed at the moment.
	if err := r.refreshStatus(
		ctx,
		placement,
		latestResourceSnapshot, isLatestResourceSnapshotPresentAndUpToDate,
		isSchedulingNeeded, selectors,
		allBindings, danglingBindings,
	); err != nil {
		wrappedErr := errors.Wraps(err, "", "placementPolicy", klog.KObj(placement))
		klog.ErrorS(wrappedErr, "Failed to update placement policy status", errors.Args(wrappedErr)...)
		return ctrl.Result{}, wrappedErr
	}
	if shouldRequeue {
		return ctrl.Result{RequeueAfter: time.Second * 15}, nil
	}
	return ctrl.Result{}, nil
}

func (r *Reconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&placementv1alpha1.PlacementPolicy{}).
		Owns(&placementv1alpha1.PlacementResourceSnapshot{}).
		Owns(&placementv1alpha1.PlacementBinding{}).
		// Note: cluster claims are cluster-scoped and cannot carry an owner reference back to a
		// namespaced placement policy, so they cannot be watched via Owns(); also watch for member
		// cluster creation. For the demo, ignore both as the controller auto-requeues when there is
		// an active cluster claim.
		Complete(r)
}
