apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "infinity"]
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "20m"
            memory: "64Mi"
