apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterRebalancingRequest
metadata:
  name: example-2
spec:
  from: kind-cluster-1
  to: kind-cluster-3
  mode: SurgeFirst
  failurePolicy:
    maximumWaitDurationPerMigrationAttemptSeconds: 60
