//go:build !ignore_autogenerated

/*
Copyright 2025 The KubeFleet Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingManager) DeepCopyInto(out *BindingManager) {
	*out = *in
	if in.ObjectRefs != nil {
		in, out := &in.ObjectRefs, &out.ObjectRefs
		*out = make([]SameNamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingManager.
func (in *BindingManager) DeepCopy() *BindingManager {
	if in == nil {
		return nil
	}
	out := new(BindingManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRequest) DeepCopyInto(out *ClusterRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRequest.
func (in *ClusterRequest) DeepCopy() *ClusterRequest {
	if in == nil {
		return nil
	}
	out := new(ClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRequestList) DeepCopyInto(out *ClusterRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRequestList.
func (in *ClusterRequestList) DeepCopy() *ClusterRequestList {
	if in == nil {
		return nil
	}
	out := new(ClusterRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRequestSpec) DeepCopyInto(out *ClusterRequestSpec) {
	*out = *in
	in.ClusterSelector.DeepCopyInto(&out.ClusterSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRequestSpec.
func (in *ClusterRequestSpec) DeepCopy() *ClusterRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRequestStatus) DeepCopyInto(out *ClusterRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProvisionedClusterName != nil {
		in, out := &in.ProvisionedClusterName, &out.ProvisionedClusterName
		*out = new(string)
		**out = **in
	}
	if in.LatestObservedClusterCreationTimestamp != nil {
		in, out := &in.LatestObservedClusterCreationTimestamp, &out.LatestObservedClusterCreationTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRequestStatus.
func (in *ClusterRequestStatus) DeepCopy() *ClusterRequestStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSelector) DeepCopyInto(out *ClusterSelector) {
	*out = *in
	if in.Terms != nil {
		in, out := &in.Terms, &out.Terms
		*out = make([]LabelAndClusterPropertySelectorTerm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSelector.
func (in *ClusterSelector) DeepCopy() *ClusterSelector {
	if in == nil {
		return nil
	}
	out := new(ClusterSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossNamespaceObjectReference) DeepCopyInto(out *CrossNamespaceObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossNamespaceObjectReference.
func (in *CrossNamespaceObjectReference) DeepCopy() *CrossNamespaceObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossNamespaceObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiffDetails) DeepCopyInto(out *DiffDetails) {
	*out = *in
	if in.ObservedInMemberClusterGeneration != nil {
		in, out := &in.ObservedInMemberClusterGeneration, &out.ObservedInMemberClusterGeneration
		*out = new(int64)
		**out = **in
	}
	in.FirstDiffedObservedTimestamp.DeepCopyInto(&out.FirstDiffedObservedTimestamp)
	if in.ObservedDiffs != nil {
		in, out := &in.ObservedDiffs, &out.ObservedDiffs
		*out = make([]PatchDetail, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiffDetails.
func (in *DiffDetails) DeepCopy() *DiffDetails {
	if in == nil {
		return nil
	}
	out := new(DiffDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmOptions) DeepCopyInto(out *HelmOptions) {
	*out = *in
	if in.APIVersions != nil {
		in, out := &in.APIVersions, &out.APIVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmOptions.
func (in *HelmOptions) DeepCopy() *HelmOptions {
	if in == nil {
		return nil
	}
	out := new(HelmOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelAndClusterPropertySelectorTerm) DeepCopyInto(out *LabelAndClusterPropertySelectorTerm) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchLabelExpressions != nil {
		in, out := &in.MatchLabelExpressions, &out.MatchLabelExpressions
		*out = make([]LabelClusterPropertyExpression, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchClusterPropertyExpressions != nil {
		in, out := &in.MatchClusterPropertyExpressions, &out.MatchClusterPropertyExpressions
		*out = make([]LabelClusterPropertyExpression, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelAndClusterPropertySelectorTerm.
func (in *LabelAndClusterPropertySelectorTerm) DeepCopy() *LabelAndClusterPropertySelectorTerm {
	if in == nil {
		return nil
	}
	out := new(LabelAndClusterPropertySelectorTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelClusterPropertyExpression) DeepCopyInto(out *LabelClusterPropertyExpression) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelClusterPropertyExpression.
func (in *LabelClusterPropertyExpression) DeepCopy() *LabelClusterPropertyExpression {
	if in == nil {
		return nil
	}
	out := new(LabelClusterPropertyExpression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Manifest) DeepCopyInto(out *Manifest) {
	*out = *in
	in.RawExtension.DeepCopyInto(&out.RawExtension)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Manifest.
func (in *Manifest) DeepCopy() *Manifest {
	if in == nil {
		return nil
	}
	out := new(Manifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestIdentifier) DeepCopyInto(out *ManifestIdentifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestIdentifier.
func (in *ManifestIdentifier) DeepCopy() *ManifestIdentifier {
	if in == nil {
		return nil
	}
	out := new(ManifestIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifact) DeepCopyInto(out *OCIArtifact) {
	*out = *in
	if in.AuthProvider != nil {
		in, out := &in.AuthProvider, &out.AuthProvider
		*out = new(OCIArtifactAuthProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.RetrievalPolicy != nil {
		in, out := &in.RetrievalPolicy, &out.RetrievalPolicy
		*out = new(OCIArtifactRetrievalPolicy)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(OCIArtifactReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifact.
func (in *OCIArtifact) DeepCopy() *OCIArtifact {
	if in == nil {
		return nil
	}
	out := new(OCIArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactAuthProvider) DeepCopyInto(out *OCIArtifactAuthProvider) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(CrossNamespaceObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactAuthProvider.
func (in *OCIArtifactAuthProvider) DeepCopy() *OCIArtifactAuthProvider {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactAuthProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactDetails) DeepCopyInto(out *OCIArtifactDetails) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Layers != nil {
		in, out := &in.Layers, &out.Layers
		*out = make([]OCIArtifactLayerDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactDetails.
func (in *OCIArtifactDetails) DeepCopy() *OCIArtifactDetails {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactLayerDetails) DeepCopyInto(out *OCIArtifactLayerDetails) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactLayerDetails.
func (in *OCIArtifactLayerDetails) DeepCopy() *OCIArtifactLayerDetails {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactLayerDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactLayerDigestAndPath) DeepCopyInto(out *OCIArtifactLayerDigestAndPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactLayerDigestAndPath.
func (in *OCIArtifactLayerDigestAndPath) DeepCopy() *OCIArtifactLayerDigestAndPath {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactLayerDigestAndPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactLayerSelector) DeepCopyInto(out *OCIArtifactLayerSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactLayerSelector.
func (in *OCIArtifactLayerSelector) DeepCopy() *OCIArtifactLayerSelector {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactLayerSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactReference) DeepCopyInto(out *OCIArtifactReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactReference.
func (in *OCIArtifactReference) DeepCopy() *OCIArtifactReference {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIArtifactRetrievalPolicy) DeepCopyInto(out *OCIArtifactRetrievalPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIArtifactRetrievalPolicy.
func (in *OCIArtifactRetrievalPolicy) DeepCopy() *OCIArtifactRetrievalPolicy {
	if in == nil {
		return nil
	}
	out := new(OCIArtifactRetrievalPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASHelmChart) DeepCopyInto(out *ORASHelmChart) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASHelmChart.
func (in *ORASHelmChart) DeepCopy() *ORASHelmChart {
	if in == nil {
		return nil
	}
	out := new(ORASHelmChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ORASHelmChart) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASHelmChartSpec) DeepCopyInto(out *ORASHelmChartSpec) {
	*out = *in
	if in.OCIArtifactRef != nil {
		in, out := &in.OCIArtifactRef, &out.OCIArtifactRef
		*out = new(OCIArtifact)
		(*in).DeepCopyInto(*out)
	}
	if in.HelmOptions != nil {
		in, out := &in.HelmOptions, &out.HelmOptions
		*out = new(HelmOptions)
		(*in).DeepCopyInto(*out)
	}
	in.Values.DeepCopyInto(&out.Values)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASHelmChartSpec.
func (in *ORASHelmChartSpec) DeepCopy() *ORASHelmChartSpec {
	if in == nil {
		return nil
	}
	out := new(ORASHelmChartSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASHelmChartStatus) DeepCopyInto(out *ORASHelmChartStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OCIArtifactDetials != nil {
		in, out := &in.OCIArtifactDetials, &out.OCIArtifactDetials
		*out = new(OCIArtifactDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASHelmChartStatus.
func (in *ORASHelmChartStatus) DeepCopy() *ORASHelmChartStatus {
	if in == nil {
		return nil
	}
	out := new(ORASHelmChartStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASManifests) DeepCopyInto(out *ORASManifests) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASManifests.
func (in *ORASManifests) DeepCopy() *ORASManifests {
	if in == nil {
		return nil
	}
	out := new(ORASManifests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ORASManifests) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASManifestsAdditionalInfoForSnapshots) DeepCopyInto(out *ORASManifestsAdditionalInfoForSnapshots) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASManifestsAdditionalInfoForSnapshots.
func (in *ORASManifestsAdditionalInfoForSnapshots) DeepCopy() *ORASManifestsAdditionalInfoForSnapshots {
	if in == nil {
		return nil
	}
	out := new(ORASManifestsAdditionalInfoForSnapshots)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASManifestsList) DeepCopyInto(out *ORASManifestsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ORASManifests, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASManifestsList.
func (in *ORASManifestsList) DeepCopy() *ORASManifestsList {
	if in == nil {
		return nil
	}
	out := new(ORASManifestsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ORASManifestsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASManifestsProcessingOptions) DeepCopyInto(out *ORASManifestsProcessingOptions) {
	*out = *in
	if in.IgnorePaths != nil {
		in, out := &in.IgnorePaths, &out.IgnorePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASManifestsProcessingOptions.
func (in *ORASManifestsProcessingOptions) DeepCopy() *ORASManifestsProcessingOptions {
	if in == nil {
		return nil
	}
	out := new(ORASManifestsProcessingOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASManifestsSpec) DeepCopyInto(out *ORASManifestsSpec) {
	*out = *in
	if in.OCIArtifact != nil {
		in, out := &in.OCIArtifact, &out.OCIArtifact
		*out = new(OCIArtifact)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASManifestsSpec.
func (in *ORASManifestsSpec) DeepCopy() *ORASManifestsSpec {
	if in == nil {
		return nil
	}
	out := new(ORASManifestsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORASManifestsStatus) DeepCopyInto(out *ORASManifestsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OCIArtifactDetails != nil {
		in, out := &in.OCIArtifactDetails, &out.OCIArtifactDetails
		*out = new(OCIArtifactDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORASManifestsStatus.
func (in *ORASManifestsStatus) DeepCopy() *ORASManifestsStatus {
	if in == nil {
		return nil
	}
	out := new(ORASManifestsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDetail) DeepCopyInto(out *PatchDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDetail.
func (in *PatchDetail) DeepCopy() *PatchDetail {
	if in == nil {
		return nil
	}
	out := new(PatchDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerManifestStatus) DeepCopyInto(out *PerManifestStatus) {
	*out = *in
	out.Identifier = in.Identifier
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiffDetails != nil {
		in, out := &in.DiffDetails, &out.DiffDetails
		*out = new(DiffDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerManifestStatus.
func (in *PerManifestStatus) DeepCopy() *PerManifestStatus {
	if in == nil {
		return nil
	}
	out := new(PerManifestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPlacementMigrationStatus) DeepCopyInto(out *PerPlacementMigrationStatus) {
	*out = *in
	out.PlacementBindingRef = in.PlacementBindingRef
	out.PlacementPolicyRef = in.PlacementPolicyRef
	if in.ToClusterName != nil {
		in, out := &in.ToClusterName, &out.ToClusterName
		*out = new(string)
		**out = **in
	}
	if in.ToClusterRequestName != nil {
		in, out := &in.ToClusterRequestName, &out.ToClusterRequestName
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPlacementMigrationStatus.
func (in *PerPlacementMigrationStatus) DeepCopy() *PerPlacementMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(PerPlacementMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementBinding) DeepCopyInto(out *PlacementBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementBinding.
func (in *PlacementBinding) DeepCopy() *PlacementBinding {
	if in == nil {
		return nil
	}
	out := new(PlacementBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementBindingList) DeepCopyInto(out *PlacementBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlacementBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementBindingList.
func (in *PlacementBindingList) DeepCopy() *PlacementBindingList {
	if in == nil {
		return nil
	}
	out := new(PlacementBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementBindingSpec) DeepCopyInto(out *PlacementBindingSpec) {
	*out = *in
	in.ClusterSelector.DeepCopyInto(&out.ClusterSelector)
	if in.ResourceSnapshotName != nil {
		in, out := &in.ResourceSnapshotName, &out.ResourceSnapshotName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementBindingSpec.
func (in *PlacementBindingSpec) DeepCopy() *PlacementBindingSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementBindingStatus) DeepCopyInto(out *PlacementBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedResourceSnapshotName != nil {
		in, out := &in.LastSyncedResourceSnapshotName, &out.LastSyncedResourceSnapshotName
		*out = new(string)
		**out = **in
	}
	if in.SelectedResources != nil {
		in, out := &in.SelectedResources, &out.SelectedResources
		*out = new(int32)
		**out = **in
	}
	if in.FailedToSyncResources != nil {
		in, out := &in.FailedToSyncResources, &out.FailedToSyncResources
		*out = new(int32)
		**out = **in
	}
	if in.UnavailableResources != nil {
		in, out := &in.UnavailableResources, &out.UnavailableResources
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementBindingStatus.
func (in *PlacementBindingStatus) DeepCopy() *PlacementBindingStatus {
	if in == nil {
		return nil
	}
	out := new(PlacementBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementMigrationFailurePolicy) DeepCopyInto(out *PlacementMigrationFailurePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementMigrationFailurePolicy.
func (in *PlacementMigrationFailurePolicy) DeepCopy() *PlacementMigrationFailurePolicy {
	if in == nil {
		return nil
	}
	out := new(PlacementMigrationFailurePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementMigrationRequest) DeepCopyInto(out *PlacementMigrationRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementMigrationRequest.
func (in *PlacementMigrationRequest) DeepCopy() *PlacementMigrationRequest {
	if in == nil {
		return nil
	}
	out := new(PlacementMigrationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementMigrationRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementMigrationRequestList) DeepCopyInto(out *PlacementMigrationRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlacementMigrationRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementMigrationRequestList.
func (in *PlacementMigrationRequestList) DeepCopy() *PlacementMigrationRequestList {
	if in == nil {
		return nil
	}
	out := new(PlacementMigrationRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementMigrationRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementMigrationRequestSpec) DeepCopyInto(out *PlacementMigrationRequestSpec) {
	*out = *in
	if in.PlacementPolicySelectors != nil {
		in, out := &in.PlacementPolicySelectors, &out.PlacementPolicySelectors
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.FromClusterSelector != nil {
		in, out := &in.FromClusterSelector, &out.FromClusterSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ToClusterSelector.DeepCopyInto(&out.ToClusterSelector)
	if in.MaxConcurrency != nil {
		in, out := &in.MaxConcurrency, &out.MaxConcurrency
		*out = new(int32)
		**out = **in
	}
	out.FailurePolicy = in.FailurePolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementMigrationRequestSpec.
func (in *PlacementMigrationRequestSpec) DeepCopy() *PlacementMigrationRequestSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementMigrationRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementMigrationRequestStatus) DeepCopyInto(out *PlacementMigrationRequestStatus) {
	*out = *in
	if in.PlacementsToMigrate != nil {
		in, out := &in.PlacementsToMigrate, &out.PlacementsToMigrate
		*out = make([]PerPlacementMigrationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementMigrationRequestStatus.
func (in *PlacementMigrationRequestStatus) DeepCopy() *PlacementMigrationRequestStatus {
	if in == nil {
		return nil
	}
	out := new(PlacementMigrationRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementPolicy) DeepCopyInto(out *PlacementPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementPolicy.
func (in *PlacementPolicy) DeepCopy() *PlacementPolicy {
	if in == nil {
		return nil
	}
	out := new(PlacementPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementPolicyList) DeepCopyInto(out *PlacementPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlacementPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementPolicyList.
func (in *PlacementPolicyList) DeepCopy() *PlacementPolicyList {
	if in == nil {
		return nil
	}
	out := new(PlacementPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementPolicySpec) DeepCopyInto(out *PlacementPolicySpec) {
	*out = *in
	if in.ClusterSelectors != nil {
		in, out := &in.ClusterSelectors, &out.ClusterSelectors
		*out = make([]ClusterSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceSelectors != nil {
		in, out := &in.ResourceSelectors, &out.ResourceSelectors
		*out = make([]SameNamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ResourceRevisionHistoryLimit != nil {
		in, out := &in.ResourceRevisionHistoryLimit, &out.ResourceRevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.SyncStrategy != nil {
		in, out := &in.SyncStrategy, &out.SyncStrategy
		*out = new(SyncStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]Toleration, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementPolicySpec.
func (in *PlacementPolicySpec) DeepCopy() *PlacementPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PlacementPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementPolicyStatus) DeepCopyInto(out *PlacementPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LatestResourceRevisionName != nil {
		in, out := &in.LatestResourceRevisionName, &out.LatestResourceRevisionName
		*out = new(string)
		**out = **in
	}
	if in.DesiredClusters != nil {
		in, out := &in.DesiredClusters, &out.DesiredClusters
		*out = new(int32)
		**out = **in
	}
	if in.NotYetScheduledClusters != nil {
		in, out := &in.NotYetScheduledClusters, &out.NotYetScheduledClusters
		*out = new(int32)
		**out = **in
	}
	if in.ResourcesOutOfSyncClusters != nil {
		in, out := &in.ResourcesOutOfSyncClusters, &out.ResourcesOutOfSyncClusters
		*out = new(int32)
		**out = **in
	}
	if in.ResourcesUnavailableClusters != nil {
		in, out := &in.ResourcesUnavailableClusters, &out.ResourcesUnavailableClusters
		*out = new(int32)
		**out = **in
	}
	if in.OngoingClusterRequests != nil {
		in, out := &in.OngoingClusterRequests, &out.OngoingClusterRequests
		*out = new(int32)
		**out = **in
	}
	if in.BindingManager != nil {
		in, out := &in.BindingManager, &out.BindingManager
		*out = new(BindingManager)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementPolicyStatus.
func (in *PlacementPolicyStatus) DeepCopy() *PlacementPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PlacementPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementResourceSnapshot) DeepCopyInto(out *PlacementResourceSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementResourceSnapshot.
func (in *PlacementResourceSnapshot) DeepCopy() *PlacementResourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(PlacementResourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementResourceSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementResourceSnapshotList) DeepCopyInto(out *PlacementResourceSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlacementResourceSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementResourceSnapshotList.
func (in *PlacementResourceSnapshotList) DeepCopy() *PlacementResourceSnapshotList {
	if in == nil {
		return nil
	}
	out := new(PlacementResourceSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementResourceSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementResourceSnapshotRequest) DeepCopyInto(out *PlacementResourceSnapshotRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementResourceSnapshotRequest.
func (in *PlacementResourceSnapshotRequest) DeepCopy() *PlacementResourceSnapshotRequest {
	if in == nil {
		return nil
	}
	out := new(PlacementResourceSnapshotRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementResourceSnapshotRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementResourceSnapshotRequestList) DeepCopyInto(out *PlacementResourceSnapshotRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlacementResourceSnapshotRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementResourceSnapshotRequestList.
func (in *PlacementResourceSnapshotRequestList) DeepCopy() *PlacementResourceSnapshotRequestList {
	if in == nil {
		return nil
	}
	out := new(PlacementResourceSnapshotRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlacementResourceSnapshotRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementResourceSnapshotRequestSpec) DeepCopyInto(out *PlacementResourceSnapshotRequestSpec) {
	*out = *in
	out.PlacementPolicyRef = in.PlacementPolicyRef
	if in.TTLSeconds != nil {
		in, out := &in.TTLSeconds, &out.TTLSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementResourceSnapshotRequestSpec.
func (in *PlacementResourceSnapshotRequestSpec) DeepCopy() *PlacementResourceSnapshotRequestSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementResourceSnapshotRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementResourceSnapshotRequestStatus) DeepCopyInto(out *PlacementResourceSnapshotRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementResourceSnapshotRequestStatus.
func (in *PlacementResourceSnapshotRequestStatus) DeepCopy() *PlacementResourceSnapshotRequestStatus {
	if in == nil {
		return nil
	}
	out := new(PlacementResourceSnapshotRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementResourceSnapshotSpec) DeepCopyInto(out *PlacementResourceSnapshotSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementResourceSnapshotSpec.
func (in *PlacementResourceSnapshotSpec) DeepCopy() *PlacementResourceSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementResourceSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceContent) DeepCopyInto(out *ResourceContent) {
	*out = *in
	out.Identifier = in.Identifier
	in.Manifest.DeepCopyInto(&out.Manifest)
	if in.AdditionalInfo != nil {
		in, out := &in.AdditionalInfo, &out.AdditionalInfo
		*out = make(map[string][]byte, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]byte, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceContent.
func (in *ResourceContent) DeepCopy() *ResourceContent {
	if in == nil {
		return nil
	}
	out := new(ResourceContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunGetRequest) DeepCopyInto(out *RunGetRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunGetRequest.
func (in *RunGetRequest) DeepCopy() *RunGetRequest {
	if in == nil {
		return nil
	}
	out := new(RunGetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunGetRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunGetRequestList) DeepCopyInto(out *RunGetRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunGetRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunGetRequestList.
func (in *RunGetRequestList) DeepCopy() *RunGetRequestList {
	if in == nil {
		return nil
	}
	out := new(RunGetRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunGetRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunGetRequestSpec) DeepCopyInto(out *RunGetRequestSpec) {
	*out = *in
	if in.LabelMatchers != nil {
		in, out := &in.LabelMatchers, &out.LabelMatchers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunGetRequestSpec.
func (in *RunGetRequestSpec) DeepCopy() *RunGetRequestSpec {
	if in == nil {
		return nil
	}
	out := new(RunGetRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunGetRequestStatus) DeepCopyInto(out *RunGetRequestStatus) {
	*out = *in
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunGetRequestStatus.
func (in *RunGetRequestStatus) DeepCopy() *RunGetRequestStatus {
	if in == nil {
		return nil
	}
	out := new(RunGetRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SameNamespacedObjectReference) DeepCopyInto(out *SameNamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SameNamespacedObjectReference.
func (in *SameNamespacedObjectReference) DeepCopy() *SameNamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(SameNamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSideApplyOptions) DeepCopyInto(out *ServerSideApplyOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSideApplyOptions.
func (in *ServerSideApplyOptions) DeepCopy() *ServerSideApplyOptions {
	if in == nil {
		return nil
	}
	out := new(ServerSideApplyOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncStrategy) DeepCopyInto(out *SyncStrategy) {
	*out = *in
	if in.ServerSideApplyOptions != nil {
		in, out := &in.ServerSideApplyOptions, &out.ServerSideApplyOptions
		*out = new(ServerSideApplyOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncStrategy.
func (in *SyncStrategy) DeepCopy() *SyncStrategy {
	if in == nil {
		return nil
	}
	out := new(SyncStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Toleration) DeepCopyInto(out *Toleration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Toleration.
func (in *Toleration) DeepCopy() *Toleration {
	if in == nil {
		return nil
	}
	out := new(Toleration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Work) DeepCopyInto(out *Work) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Work.
func (in *Work) DeepCopy() *Work {
	if in == nil {
		return nil
	}
	out := new(Work)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Work) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkList) DeepCopyInto(out *WorkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Work, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkList.
func (in *WorkList) DeepCopy() *WorkList {
	if in == nil {
		return nil
	}
	out := new(WorkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkSpec) DeepCopyInto(out *WorkSpec) {
	*out = *in
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]Manifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SyncStrategy != nil {
		in, out := &in.SyncStrategy, &out.SyncStrategy
		*out = new(SyncStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkSpec.
func (in *WorkSpec) DeepCopy() *WorkSpec {
	if in == nil {
		return nil
	}
	out := new(WorkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkStatus) DeepCopyInto(out *WorkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]PerManifestStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkStatus.
func (in *WorkStatus) DeepCopy() *WorkStatus {
	if in == nil {
		return nil
	}
	out := new(WorkStatus)
	in.DeepCopyInto(out)
	return out
}
