//go:build !ignore_autogenerated

/*
Copyright 2025 The KubeFleet Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityRequestPerPod) DeepCopyInto(out *CapacityRequestPerPod) {
	*out = *in
	if in.NodeInstanceRequests != nil {
		in, out := &in.NodeInstanceRequests, &out.NodeInstanceRequests
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.ResourceRequests != nil {
		in, out := &in.ResourceRequests, &out.ResourceRequests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityRequestPerPod.
func (in *CapacityRequestPerPod) DeepCopy() *CapacityRequestPerPod {
	if in == nil {
		return nil
	}
	out := new(CapacityRequestPerPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterNodePool) DeepCopyInto(out *MultiClusterNodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterNodePool.
func (in *MultiClusterNodePool) DeepCopy() *MultiClusterNodePool {
	if in == nil {
		return nil
	}
	out := new(MultiClusterNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiClusterNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterNodePoolList) DeepCopyInto(out *MultiClusterNodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiClusterNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterNodePoolList.
func (in *MultiClusterNodePoolList) DeepCopy() *MultiClusterNodePoolList {
	if in == nil {
		return nil
	}
	out := new(MultiClusterNodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiClusterNodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterNodePoolSpec) DeepCopyInto(out *MultiClusterNodePoolSpec) {
	*out = *in
	if in.NodeClassRef != nil {
		in, out := &in.NodeClassRef, &out.NodeClassRef
		*out = new(string)
		**out = **in
	}
	if in.ClusterClassRef != nil {
		in, out := &in.ClusterClassRef, &out.ClusterClassRef
		*out = new(string)
		**out = **in
	}
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(NodeCount)
		**out = **in
	}
	if in.ResourceLimits != nil {
		in, out := &in.ResourceLimits, &out.ResourceLimits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.NodeRequests.DeepCopyInto(&out.NodeRequests)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterNodePoolSpec.
func (in *MultiClusterNodePoolSpec) DeepCopy() *MultiClusterNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(MultiClusterNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterNodePoolStatus) DeepCopyInto(out *MultiClusterNodePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceCapacities != nil {
		in, out := &in.ResourceCapacities, &out.ResourceCapacities
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.ResourceRequests != nil {
		in, out := &in.ResourceRequests, &out.ResourceRequests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterNodePoolStatus.
func (in *MultiClusterNodePoolStatus) DeepCopy() *MultiClusterNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(MultiClusterNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCount) DeepCopyInto(out *NodeCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCount.
func (in *NodeCount) DeepCopy() *NodeCount {
	if in == nil {
		return nil
	}
	out := new(NodeCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRequests) DeepCopyInto(out *NodeRequests) {
	*out = *in
	if in.NodeSizes != nil {
		in, out := &in.NodeSizes, &out.NodeSizes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRequests.
func (in *NodeRequests) DeepCopy() *NodeRequests {
	if in == nil {
		return nil
	}
	out := new(NodeRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SameNamespacedObjectReference) DeepCopyInto(out *SameNamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SameNamespacedObjectReference.
func (in *SameNamespacedObjectReference) DeepCopy() *SameNamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(SameNamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPlacement) DeepCopyInto(out *WorkloadPlacement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPlacement.
func (in *WorkloadPlacement) DeepCopy() *WorkloadPlacement {
	if in == nil {
		return nil
	}
	out := new(WorkloadPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadPlacement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPlacementList) DeepCopyInto(out *WorkloadPlacementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadPlacement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPlacementList.
func (in *WorkloadPlacementList) DeepCopy() *WorkloadPlacementList {
	if in == nil {
		return nil
	}
	out := new(WorkloadPlacementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadPlacementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPlacementSpec) DeepCopyInto(out *WorkloadPlacementSpec) {
	*out = *in
	if in.MultiClusterNodePoolSelecter != nil {
		in, out := &in.MultiClusterNodePoolSelecter, &out.MultiClusterNodePoolSelecter
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	out.WorkloadRef = in.WorkloadRef
	if in.AdditionalResourceRefs != nil {
		in, out := &in.AdditionalResourceRefs, &out.AdditionalResourceRefs
		*out = make([]SameNamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.CapacityRequest != nil {
		in, out := &in.CapacityRequest, &out.CapacityRequest
		*out = new(CapacityRequestPerPod)
		(*in).DeepCopyInto(*out)
	}
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPlacementSpec.
func (in *WorkloadPlacementSpec) DeepCopy() *WorkloadPlacementSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadPlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPlacementStatus) DeepCopyInto(out *WorkloadPlacementStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LatestResourceSnapshotRevisionName != nil {
		in, out := &in.LatestResourceSnapshotRevisionName, &out.LatestResourceSnapshotRevisionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPlacementStatus.
func (in *WorkloadPlacementStatus) DeepCopy() *WorkloadPlacementStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadPlacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceClusterBinding) DeepCopyInto(out *WorkloadResourceClusterBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceClusterBinding.
func (in *WorkloadResourceClusterBinding) DeepCopy() *WorkloadResourceClusterBinding {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceClusterBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadResourceClusterBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceClusterBindingList) DeepCopyInto(out *WorkloadResourceClusterBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadResourceClusterBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceClusterBindingList.
func (in *WorkloadResourceClusterBindingList) DeepCopy() *WorkloadResourceClusterBindingList {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceClusterBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadResourceClusterBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceClusterBindingSpec) DeepCopyInto(out *WorkloadResourceClusterBindingSpec) {
	*out = *in
	if in.MemberClusterName != nil {
		in, out := &in.MemberClusterName, &out.MemberClusterName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceClusterBindingSpec.
func (in *WorkloadResourceClusterBindingSpec) DeepCopy() *WorkloadResourceClusterBindingSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceClusterBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceClusterBindingStatus) DeepCopyInto(out *WorkloadResourceClusterBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceClusterBindingStatus.
func (in *WorkloadResourceClusterBindingStatus) DeepCopy() *WorkloadResourceClusterBindingStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceClusterBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceNodePoolBinding) DeepCopyInto(out *WorkloadResourceNodePoolBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceNodePoolBinding.
func (in *WorkloadResourceNodePoolBinding) DeepCopy() *WorkloadResourceNodePoolBinding {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceNodePoolBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadResourceNodePoolBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceNodePoolBindingList) DeepCopyInto(out *WorkloadResourceNodePoolBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadResourceNodePoolBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceNodePoolBindingList.
func (in *WorkloadResourceNodePoolBindingList) DeepCopy() *WorkloadResourceNodePoolBindingList {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceNodePoolBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadResourceNodePoolBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceNodePoolBindingSpec) DeepCopyInto(out *WorkloadResourceNodePoolBindingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceNodePoolBindingSpec.
func (in *WorkloadResourceNodePoolBindingSpec) DeepCopy() *WorkloadResourceNodePoolBindingSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceNodePoolBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceNodePoolBindingStatus) DeepCopyInto(out *WorkloadResourceNodePoolBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceNodePoolBindingStatus.
func (in *WorkloadResourceNodePoolBindingStatus) DeepCopy() *WorkloadResourceNodePoolBindingStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceNodePoolBindingStatus)
	in.DeepCopyInto(out)
	return out
}
