apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-2
  namespace: work
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pause-2
  template:
    metadata:
      labels:
        app: pause-2
    spec:
      containers:
        - name: pause
          image: k8s.gcr.io/pause:3.2
          ports:
            - containerPort: 80
