#!/bin/bash
# This script port-forwards to a vcluster's API server Service so that the vcluster's
# kubeconfig (as generated by "setup-vcluster.sh") can be used from the local machine. It waits
# until the vcluster's API server Service is assigned a cluster IP, patches the kubeconfig to
# point at a "https://localhost:<port>" address, then starts port-forwarding to the Service
# through that same address. The port-forward runs in the foreground until interrupted
# (e.g. with Ctrl+C).
#
# Usage:
#     ./port-forward.sh [vcluster-name] [local-port]
#
# Example:
#     ./port-forward.sh tenant-a 18443
#
# Requirements:
#     - kubectl must be installed and available in PATH
#     - the current kubectl context must point to the host cluster of the vcluster
#     - the vcluster's kubeconfig ("<vcluster-name>.kubeconfig") must already exist in the
#       current working directory (see setup-vcluster.sh)
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
    ./port-forward.sh [vcluster-name] [local-port]

Example:
    ./port-forward.sh tenant-a 18443

Requirements:
    - kubectl must be installed and available in PATH
    - the current kubectl context must point to the host cluster of the vcluster
    - the vcluster's kubeconfig ("<vcluster-name>.kubeconfig") must already exist in the
      current working directory (see setup-vcluster.sh)
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
fi

if ! command -v kubectl >/dev/null 2>&1; then
    echo "Error: kubectl is not installed or not available in PATH" >&2
    exit 1
fi

# Portable in-place sed: macOS requires an explicit backup extension with -i,
# while GNU sed (Linux) treats an empty string as no backup.
sed_in_place() {
    if sed --version 2>/dev/null | grep -q 'GNU'; then
        sed -i "$@"
    else
        sed -i '' "$@"
    fi
}

VCLUSTER_NAME=${1:-multitenancy-demo}
LOCAL_PORT=${2:-8443}
# Each vcluster is deployed into its own namespace, named after the vcluster itself; see
# setup-vcluster.sh.
VCLUSTER_NAMESPACE=$VCLUSTER_NAME
KUBECONFIG_FILE="$(pwd)/$VCLUSTER_NAME.kubeconfig"

case "$LOCAL_PORT" in
    ''|*[!0-9]*)
        echo "Error: local port must be a positive integer, got \"$LOCAL_PORT\"" >&2
        exit 1
        ;;
esac

if [ ! -f "$KUBECONFIG_FILE" ]; then
    echo "Error: kubeconfig file not found at $KUBECONFIG_FILE; run setup-vcluster.sh first" >&2
    exit 1
fi

echo "Patching $KUBECONFIG_FILE to use https://localhost:$LOCAL_PORT..."
sed_in_place "s|https://localhost:[0-9]*|https://localhost:$LOCAL_PORT|g" "$KUBECONFIG_FILE"

echo "Starting port-forwarding to svc/$VCLUSTER_NAME (localhost:$LOCAL_PORT -> 443). Press Ctrl+C to stop."
echo "In another terminal, use the vcluster with: export KUBECONFIG=$KUBECONFIG_FILE"
kubectl port-forward -n "$VCLUSTER_NAMESPACE" "svc/$VCLUSTER_NAME" "$LOCAL_PORT:443"
